spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/yyets.db
  mvc:
    view:
      suffix: .html
      prefix: /
    static-path-pattern: /**
logging:
  level:
    root: info
  file:
    name: /var/logs/yyets-history.log
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 9000
yyets-history:
  link-way-filter: #保留的链接类型
    - 电驴
    - 磁力
  default-page-size: 20 #默认的查询数量