spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/yyets.db
  mvc:
    view:
      suffix: .html
      prefix: /
    static-path-pattern: /**
logging:
  level:
    root: info
  #    "com.zhangjiashuai.yyetshistory.repository": debug
  file:
    name: logs/yyets-history.log
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  dialect-alias: sqlite
server:
  port: 9000
yyets-history:
  link-way-filter: #保留的链接类型
    - 电驴
    - 磁力
  host: localhost # 域名
  start-finish-event: true # 是否触发启动成功事件